export enum Variables {
  STORAGE_AUTH = "TOKEN",
  USER_LOGIN = "USER_LOGIN",
  USER_AUTH = "USER_AUTH",
  IP_USER = "IP_USER",
  PERMISSIONS = "PERMISSIONS",
  ROLES = "ROLES",
  MENU = "MENU",
  USER = "USER",
  TEXTHEADER = "SELECIONE UMA CATEGORIA",
  REFRESH_TOKEN = "REFRESH_TOKEN",
  AUTH_TOKEN_EXPIRES_AT = "AUTH_TOKEN_EXPIRES_AT",
}
